# Generated by Django 3.2.10 on 2022-03-14 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro_service', '0005_agro_image'),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('image', models.ImageField(upload_to='acart')),
                ('agro', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='agro_service.agro')),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='agro_service.acateg')),
                ('farmer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='farmer.farmermanage')),
            ],
        ),
    ]
