# Generated by Django 3.2.10 on 2022-03-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_acart'),
    ]

    operations = [
        migrations.AddField(
            model_name='acart',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
