# Generated by Django 3.2.10 on 2022-03-14 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_acart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acart',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
