# Generated by Django 3.2.10 on 2022-03-14 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0011_krishimanage_image'),
        ('agro_service', '0005_agro_image'),
        ('farmer', '0004_acart_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('image', models.ImageField(upload_to='acart')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='agro_service.acateg')),
                ('farmer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='farmer.farmermanage')),
                ('krishi', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='krishibhavan.krishimanage')),
            ],
        ),
    ]
