# Generated by Django 3.2.10 on 2022-03-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0011_krishimanage_image'),
        ('farmer', '0005_kcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcart',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='krishibhavan.categ'),
        ),
    ]
