# Generated by Django 3.2.10 on 2022-03-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_alter_kcart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcart',
            name='image',
            field=models.ImageField(upload_to='kcart'),
        ),
    ]
