# Generated by Django 3.2.5 on 2022-03-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_alter_kcart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmermanage',
            name='proof',
            field=models.ImageField(default=0, upload_to='image'),
        ),
    ]
