# Generated by Django 3.2.5 on 2022-03-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_farmermanage_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchoProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('pdesc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='image')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmermanage')),
            ],
        ),
    ]
