# Generated by Django 3.2.5 on 2022-03-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_echoproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='echoproducts',
            name='categ',
            field=models.TextField(default=0),
        ),
    ]
