# Generated by Django 3.2.5 on 2022-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_echoproducts_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmermanage',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
