# Generated by Django 3.2.5 on 2022-03-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmanage',
            name='status',
        ),
    ]
