# Generated by Django 3.2.5 on 2022-03-29 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_farmermanage_image'),
        ('client', '0002_remove_clientmanage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('image', models.ImageField(upload_to='ecart')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='farmer.farmermanage')),
            ],
        ),
    ]
