# Generated by Django 3.2.5 on 2022-03-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_ecart'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecart',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='client.clientmanage'),
        ),
    ]
