# Generated by Django 3.2.10 on 2022-03-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agroname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('mobno', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
