# Generated by Django 3.2.10 on 2022-03-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('krishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro_service.agro')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('pdesc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='image')),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='agro_service.categ')),
                ('krishi', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='agro_service.agro')),
            ],
        ),
    ]
