# Generated by Django 3.2.10 on 2022-03-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro_service', '0002_categ_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categ',
            old_name='krishi',
            new_name='agro',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='krishi',
            new_name='agro',
        ),
    ]
