# Generated by Django 3.2.10 on 2022-03-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro_service', '0003_auto_20220313_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categ',
            new_name='ACateg',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='AProducts',
        ),
    ]
