# Generated by Django 3.2.10 on 2022-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_service', '0004_auto_20220313_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='agro',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
