# Generated by Django 3.2.10 on 2022-01-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgroProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('pdesc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='image')),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdesc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='image')),
                ('pname', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='krishimanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayath', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('mobno', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdesc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='image')),
                ('pname', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
