# Generated by Django 3.2.10 on 2022-01-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agroproduct',
            name='available',
        ),
        migrations.RemoveField(
            model_name='agroproduct',
            name='name',
        ),
        migrations.AddField(
            model_name='agroproduct',
            name='pname',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
