# Generated by Django 3.2.5 on 2022-02-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0002_auto_20220113_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='agrofertilizerseed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdesc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='image')),
                ('pname', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
