# Generated by Django 3.2.5 on 2022-03-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0003_agrofertilizerseed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FertilizerSeed',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='agrofertilizerseed',
        ),
        migrations.DeleteModel(
            name='AgroProduct',
        ),
        migrations.DeleteModel(
            name='PlantDetails',
        ),
    ]
