# Generated by Django 3.2.5 on 2022-03-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0004_auto_20220305_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('krishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishibhavan.krishimanage')),
            ],
        ),
    ]
