# Generated by Django 3.2.5 on 2022-03-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0005_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categ',
        ),
    ]
