# Generated by Django 3.2.5 on 2022-03-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0007_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('pdesc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='image')),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='krishibhavan.categ')),
            ],
        ),
    ]
