# Generated by Django 3.2.10 on 2022-03-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0008_auto_20220305_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
