# Generated by Django 3.2.10 on 2022-03-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0009_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='krishi',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='krishibhavan.krishimanage'),
        ),
    ]
