# Generated by Django 3.2.10 on 2022-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0010_products_krishi'),
    ]

    operations = [
        migrations.AddField(
            model_name='krishimanage',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
