# Generated by Django 3.2.10 on 2022-03-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishibhavan', '0011_krishimanage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishibhavan.categ'),
        ),
        migrations.AlterField(
            model_name='products',
            name='krishi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishibhavan.krishimanage'),
        ),
    ]
